### ISSUE TITLE
Install was correct. Does not work.

### ISSUE THREAD

**Issue by farmascript** [cosmocode/dokuwiki-plugin-tablelayout#3]
Installation via plugin-manager in dokuwiki was ok.
Plugin boiler-plate does not do anything.
Table layout was shown ok, but probably due to the basic table features of dokuwiki. Conflicting plugins, mentioned in the doc, not installed.

**Comment by M-ax-G** [comment]
Sorry to say: Same here...
1. Installation via plugin-manager in dokuwiki was successful.
2. Copied Plugin boiler-plate; does not do anything.
However, table layout was shown OK, most likely due to the basic table features of dokuwiki.
3. Conflicting plugins, mentioned in the doc, are not installed.

**Comment by micgro42** [comment]
The Plugin uses javascript to apply the functionality. Please see the javascript error-console for any errors.

**Comment by M-ax-G** [comment]
JavaConsole does not show any errors...

Using the demo code as per doc:
{{tablelayout?colwidth="20px,30px"&rowsHeaderSource=1&rowsVisible=2&float=right}}
{{tablelayout?colwidth="100px,50px"&rowsHeaderSource=1&rowsVisible=2&float=right}}


![image](https://user-images.githubusercontent.com/21173730/33577546-171bd992-d98f-11e7-8848-ec8c20427c2a.png)

**Comment by bttrx** [comment]
Same here.
Running a fresh install of DW 2017-02-19e "Frusterick Manners" with only the move (and tablelayout) plugins installed.
Tried Firefox 50 and Chrome 49.

**Comment by M-ax-G** [comment]
Yes, should have stated my environment as well, sorry.
dokuwiki runs on xampp; installed based on previous version, running fine ever since; has Frusterick update; then installed tablelayout via extension manager; happy to pull info if instructed what is required.
Desktop: Windows 10 with FF 57.0.1 64-bit; Chrome Version 62.0.3202.94 (Official Build) (64-bit); PaleMoon 27.6.2 (32-bit).
As mentioned earlier, am happy to collaborate on providing info about the system it runs on.

**Comment by micgro42** [comment]
Thank you, I can partly reproduce it one system but not on another. Do you happen to have the edittable-plugin installed? If so, do you see the button to edit tables?

**Comment by M-ax-G** [comment]
I don't have it installed, but can if you want me to.

**Comment by farmascript** [comment]
Here: edittable is installed, button is visible. Tablelayout does not work.

**Comment by farmascript** [comment]
Just did the update 2017-11-30. Does not work either. Getting worse... :-) :  the normal basic table-layout is now also not working any more...

**Comment by micgro42** [comment]
Please update to the current version. It should work there now 🙂

**Comment by M-ax-G** [comment]
It does; thank you :)

**Comment by bttrx** [comment]
Works for me too. (No edittable plugin here.)

**Comment by farmascript** [comment]
![tablelayout0](https://user-images.githubusercontent.com/1309793/33804694-8d8d2ea4-ddaa-11e7-9cb1-d2806894d372.png)

Hmm... Does not work.
Seems that the {{...}} combination is hijacked bij another utility before tablelayout can process it...

**Comment by farmascript** [comment]
plugins 'addnewpage' and indexmenu' are also using {{}}. But desactivating them does not solve the problem either.

[https://www.dokuwiki.org/plugin:addnewpage]
[https://www.dokuwiki.org/plugin:indexmenu]

**Comment by farmascript** [comment]
Works ok now.
